name: Auto Translate

on:
  push:
    paths:
      - 'locales/*.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  translate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lang: [fr, el]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # needed for git diff

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install openai

      - name: Run translation script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TARGET_LANG: ${{ matrix.lang }}
        run: python -u scripts/auto_translate.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add locales
          git commit -m "Auto-translated for ${{ matrix.lang }}" || echo "No changes for ${{ matrix.lang }}"
          git push
